feat: use the body variable with templayed
bettyblocks/block-store-action-functions pull request #53
Opened 2022-10-13 18:03 UTC by mgeerse

2022-10-14 08:23 UTC, TheoHollenberg commented
I seem to be missing unit tests. Is that by design?

2022-10-14 12:05 UTC, mgeerse commented
Yes I haven't included that yet, I will add those though @TheoHollenberg!

2022-10-20 13:07 UTC, justin-betty commented
Can you expand the description a little more about what this function is doing which we can use in the block?

2022-10-28 13:20 UTC, mgeerse commented
@justin-betty I hope that this includes enough information

2022-11-01 09:55 UTC, justin-betty commented
Yes, But please add some tests

2022-11-01 18:15 UTC, mgeerse commented
I don't know how to implement a test helper for fetch.

2022-11-10 20:43 UTC, mgeerse commented
breaking on fetch not being found, I tried to add it just like over at https://github.com/bettyblocks/native-functions/blob/master/__tests__/http/1.0/index.test.js

2022-11-17 14:25 UTC, jwielinga commented on functions/http2/1.0/function.json
> +  "label": "HTTP(S) 2.0",
HTTP(S) 2.0 is not a correct name. This indicates it cannot comply with other http versions

2022-11-25 13:39 UTC, jwielinga requested changes
See comment

2022-11-25 13:39 UTC, jwielinga commented on functions/http2/1.0/templayed.js
> +// *
Should this not be a shared directory, so it can be reused by other functions. so something in e.g. utils directory

2022-11-25 13:39 UTC, jwielinga commented on functions/http2/1.0/index.js
> +  const data = await response.text();
Rename to as and return it like `return { as }`

2022-11-25 13:39 UTC, jwielinga commented on __tests__/http2/1.0/index.test.js
> +    const request = {
Would be better if request is extracted out of scope of this test function and properties that are not shared are added to it. But not blocking merging

2022-11-25 13:45 UTC, jwielinga requested changes

2022-11-25 13:45 UTC, jwielinga commented on functions/http2/1.0/templayed.js
> +// *
Maybe look at the expression step how it is done

2022-12-01 19:18 UTC, mgeerse commented
not going to bother, sorry

2022-12-01 19:18 UTC, closed without merging