Text Equals - Action step
bettyblocks/block-store-action-functions pull request #6
Opened 2022-08-17 12:38 UTC by degrootsam

2022-10-24 07:50 UTC, justin-betty commented on functions/equals-text/1.0/index.js
> +    export default equalsText;
Please add a empty line at the end

2022-10-24 07:50 UTC, justin-betty commented on test/compare-values.test.js
> +});
Please add a empty line here

2022-11-03 12:29 UTC, degrootsam commented on functions/equals-text/1.0/index.js
> +    switch (comparator) {
Check earlier comments made by Thomas

2022-11-04 12:49 UTC, justin-betty commented on functions/equals-text/1.0/index.js
> +    let res = false;
Can you do `let result;`

2022-11-04 12:50 UTC, justin-betty commented on functions/equals-text/1.0/index.js
> +        return {
Here you can do 

`return { result }`

2022-11-04 12:50 UTC, justin-betty commented on functions/equals-text/1.0/index.js
> +export default equalsText;
Add empty line at the end

2022-11-04 12:51 UTC, justin-betty commented
Can you also add a unit test

2022-11-25 13:20 UTC, jwielinga commented on functions/equals-text/1.0/index.js
> +export default equalsText;
Better if you add it to prettier

2022-11-25 13:22 UTC, jwielinga requested changes

2022-11-25 13:22 UTC, jwielinga commented on test/text-equals.test.js
> +  const result = await $app['equalsText 1.0']({ leftValue: 'Lorum Ipsum', rightValue: 'Lorum Ipsum', comparator: 'eq', toLower: false });
Don't declare the same parameter everytime. Declare shared variable if values are reused

2022-12-05 14:35 UTC, degrootsam commented
Due to fork, closed pull request. See: https://github.com/bettyblocks/block-store-action-functions/pull/83

2022-12-05 14:35 UTC, closed without merging